site_name: Dave Campbell
theme:
  name: material
  favicon: images/favicon2.ico
  logo: images/logo.png
# not using this - the feedback form gets boogered up by the hotkeys
#  custom_dir: my_theme_customizations/
# extra_javascript:
#  - https://script.bugpilot.io/3c7a8980-9739-42ed-bf3a-1f8f19cbdfcf/adopto.js

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/daveccampbell
    - icon: fontawesome/brands/github
      link: https://github.com/davecampbell
    - icon: fontawesome/solid/envelope
      link: mailto:daveccampbell@gmail.com


  analytics:
    provider: google
    property: G-QKFJ1SLQB9

nav:
    - Home: index.md
    - About: about.md
    - Personal: personal/personal.md
    - Career: career.md
    - Interests:
      - Overall: interests.md
      - ML: ml.md
    - TIL: til/index.md
      - knife sharpening: til/whetstone.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      blog_dir: til
      post_date_format: short
      post_url_date_format: yyyy/MM
      post_url_format: "{categories}/{slug}"
