site_name: Dave Campbell
theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/daveccampbell
    - icon: fontawesome/brands/github
      link: https://github.com/davecampbell
    - icon: fontawesome/solid/envelope
      link: mailto:daveccampbell@gmail.com
