site_name: Dave Campbell
theme:
  name: material
  favicon: images/favicon.png

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/daveccampbell
    - icon: fontawesome/brands/github
      link: https://github.com/davecampbell
    - icon: fontawesome/solid/envelope
      link: mailto:daveccampbell@gmail.com

nav:
    - Home: index.md
    - About: about.md
    - Personal: personal/personal.md
    - Career: career.md
    - Interests:
      - Overall: interests.md
      - ML: ml.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      